Eshop/urls.py
from django.contrib import admin
from django.urls import path  , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from .views.home import Index , store
from .views.signup import Signup
from .views.login import Login , logout
from .views.cart import Cart
from .views.orders import OrderView
from .middlewares.auth import  auth_middleware
from .views.products import ProductView
from .views.admin_dashboard import AdminView
from .views.staff_dashboard import StaffView
from .views.createuser import CreateUser
from .views.viewproducts import ViewProducts, EditProduct, NewProduct
from .views.viewcategories import ViewCategories, EditCategory, NewCategory
from .views.viewusers import ViewUsers, EditUser
from .views.vieworder import ViewOrders, EditOrder
from .views.search import SearchView
from .views.csp import CSPReportView

urlpatterns = [
    path('', Index.as_view(), name='homepage'),
    path('store', store , name='store'),
    path('signup', Signup.as_view(), name='signup'),
    path('login', Login.as_view(), name='login'),
    path('logout', logout , name='logout'),
    path('cart', auth_middleware(Cart.as_view()) , name='cart'),
    path('checkout', auth_middleware(views.cart.checkout) , name='checkout'),
    path('orders', auth_middleware(OrderView.as_view()), name='orders'),
    path('product/<int:product_id>', ProductView.as_view(), name='product'),
    path('admin_dashboard', AdminView.as_view(), name='admin_dashboard'),
    path('staff_dashboard', StaffView.as_view(), name='staff_dashboard'),
    path('create_user', CreateUser.as_view(), name='create_user'),
    path('viewproducts', ViewProducts.as_view(), name='viewproducts'),
    path('editproduct/<int:product_id>', EditProduct.as_view(), name='editproduct'),
    path('viewcategories', ViewCategories.as_view(), name='viewcategories'),
    path('editcategory/<int:category_id>', EditCategory.as_view(), name='editcategory'),
    path('new_category', NewCategory.as_view(), name='new_category'),
    path('new_product', NewProduct.as_view(), name='new_product'),
    path('viewusers', ViewUsers.as_view(), name='viewusers'),
    path('viewusers/edit/<int:user_id>/', EditUser.as_view(), name='edituser'),
    path('vieworders', ViewOrders.as_view(), name='vieworders'),
    path('editorder/edit/<int:order_id>/', EditOrder.as_view(), name='editorder'),
    path('search/', SearchView.as_view(), name='search'),
    path('csp-report/', CSPReportView.as_view(), name='csp-report'),
]

store/models/user.py
# user.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# Custom User Manager
class CustomUserManager(BaseUserManager):
    def create_user(self, username, first_name, last_name, email, phone_number, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(username=username, first_name=first_name, last_name=last_name, email=email, phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, first_name, last_name, email, phone_number, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(username, first_name, last_name, email, phone_number, password, **extra_fields)


# Custom User Model
class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["first_name", "last_name", "email", "phone_number"]

    def __str__(self):
        return self.username

    @staticmethod
    def get_user_roles(user_id):
        from .orders import UserRole
        return UserRole.objects.filter(user_id=user_id)
    
    @staticmethod
    def get_user_orders(user_id):
        from .orders import Order
        return Order.objects.filter(user_id=user_id)
    
    orders = models.ManyToManyField('store.Order', through='store.UserRole', related_name='users_as_customer')
    user = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='users_as_staff')

    groups = None  # Disable built-in groups field for the CustomUser model
    user_permissions = None


# Role Model
class Role(models.Model):
    ROLE_CHOICES = (
        ('customer', 'Customer'),
        ('staff', 'Staff'),
        ('admin', 'Admin'),
    )

    name = models.CharField(max_length=50, choices=ROLE_CHOICES, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name  


# User-Role Mapping Model
class UserRole(models.Model):
    user = models.ForeignKey('store.CustomUser', on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, default='customer')
    order = models.ForeignKey('store.Order', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.role}"

store/views/admin_dashboard.py
from django.shortcuts import render
from django.views import View
from store.models.user import CustomUser, UserRole

class AdminView(View):
    def get(self, request):
        # Get the customer ID from the session
        customer_id = request.session.get('customer')

        # If the customer ID is found, retrieve the CustomUser object
        if customer_id:
            try:
                customer = CustomUser.objects.get(id=customer_id)
                # Check if the user has the admin role
                user_roles = UserRole.objects.filter(user=customer)
                roles = []
                for user_role in user_roles:
                    role_name = user_role.role.name.lower()
                    roles.append(role_name)
                    if role_name == 'admin':
                        return render(request, 'admin_dashboard.html', {'roles': roles})
            except CustomUser.DoesNotExist:
                pass
        
        # Redirect to login or other page if the user is not an admin
        return render(request, 'login.html', {'error': 'You must be admin !!'})

store/views/cart.py
from django.shortcuts import render
from django.http import HttpResponseForbidden
import stripe
from django.views import View
from store.models.products import Products
from django.conf import settings
from store.models.user import CustomUser, UserRole
from store.models.orders import Order

stripe.api_key = settings.STRIPE_SECRET_KEY

class Cart(View):
    def get(self, request):
        customer_id = request.session.get('customer')
        roles = []
        if customer_id:
            try:
                customer = CustomUser.objects.get(id=customer_id)
                user_roles = UserRole.objects.filter(user=customer)
                for user_role in user_roles:
                    role_name = user_role.role.name.lower()
                    roles.append(role_name)
                    if role_name == 'customer':
                        ids = list(request.session.get('cart').keys())
                        products = Products.get_products_by_id(ids)
                        return render(request, 'cart.html', {'products': products, 'roles': roles})
            except CustomUser.DoesNotExist:
                pass
        return render(request, 'login.html', {'error': 'You must be a customer to view your cart!'})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLIC_KEY
        return context
    
def checkout(request):
    customer_id = request.session.get('customer')
    roles = []
    if customer_id:
        customer = CustomUser.objects.get(id=customer_id)
        user_roles = UserRole.objects.filter(user=customer)
        for user_role in user_roles:
            role_name = user_role.role.name.lower()
            roles.append(role_name)
            if role_name == 'customer':
                if request.method == "POST":
                    checkout = stripe.Charge.create(
                        amount=100,
                        currency="aud",
                        description="Payment",
                        source=request.POST['stripeToken']
                    )

                    if checkout['status'] == 'succeeded':
                        customer_id = request.session.get('customer')
                        customer = CustomUser.objects.get(id=customer_id)

                        cart = request.session.get('cart')
                        for product_id, quantity in cart.items():
                            product = Products.objects.get(id=product_id)

                            # Retrieve address and phone number from the POST data
                            address = request.POST.get('address')
                            phone = request.POST.get('phone')

                            # create order
                            order = Order(
                                product=product,
                                customer=customer,
                                user=customer,
                                quantity=quantity,
                                price=product.price,
                                address=address,
                                phone=phone,
                            )
                            order.placeOrder()

                        # Clear cart
                        request.session['cart'] = {}

                    return render(request , 'checkout.html')
                else:
                    return HttpResponseForbidden()

store/views/createuser.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError
from store.models.user import CustomUser, UserRole, Role
from django.views import View
from django.utils.decorators import method_decorator
from django.middleware.csrf import rotate_token
from django.views.decorators.csrf import csrf_protect

@method_decorator(csrf_protect, name='dispatch')
class CreateUser(View):
    def get(self, request):
        # Check if the logged-in user has the 'Admin' role
        customer_id = request.session.get('customer')
        roles = []
        if customer_id:
            try:
                customer = CustomUser.objects.get(id=customer_id)
                if UserRole.objects.filter(user=customer, role__name='Admin').exists():
                    user_roles = UserRole.objects.filter(user=customer)
                    for user_role in user_roles:
                        role_name = user_role.role.name.lower()
                        roles.append(role_name)
                    return render(request, 'createuser.html', {'roles': roles})
            except CustomUser.DoesNotExist:
                pass
        
        # Redirect to login or other page if the user does not have the required role
        return render(request, 'login.html', {'error': 'You must be admin !!'})

    def post(self, request):
        rotate_token(request)
        # Same check for 'Admin' role as in the 'get' method
        customer_id = request.session.get('customer')
        if not customer_id or not UserRole.objects.filter(user__id=customer_id, role__name='Admin').exists():
            return render(request, 'login.html', {'error': 'You must be admin !!'})

        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user_type = request.POST.get('user_type')

        # Validate the email address
        email_validator = EmailValidator()
        try:
            email_validator(email)
        except ValidationError as e:
            error_message = e.messages[0]
            data = {
                'error': error_message,
                'username': username,
                'first_name': first_name,
                'last_name': last_name,
                'phone_number': phone_number,
                'user_type': user_type,
            }
            return render(request, 'createuser.html', data)

        # Check if a user with the same email already exists
        if CustomUser.objects.filter(email=email).exists():
            error_message = 'A user with the same email already exists.'
            data = {
                'error': error_message,
                'username': username,
                'first_name': first_name,
                'last_name': last_name,
                'phone_number': phone_number,
                'user_type': user_type,
            }
            return render(request, 'createuser.html', data)

        user = CustomUser(
            username=username,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            email=email,
            password=make_password(password),
            is_staff=user_type == 'STAFF',
            is_admin=user_type == 'ADMIN',
        )
        user.save()

        role_name = user_type.title()
        role = Role.objects.get(name=role_name)

        user_role = UserRole(user=user, role=role)
        user_role.save()

        return redirect('admin_dashboard')

store/views/csp.py
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views import View

@method_decorator(csrf_exempt, name='dispatch')
class CSPReportView(View):
    def post(self, request, *args, **kwargs):
        try:
            report_data = json.loads(request.body.decode('utf-8'))

            # Log the report data to a file
            with open('csp-reports.txt', 'a') as file:
                file.write(json.dumps(report_data) + '\n')

            # Optionally, you can also print the report data
            print(report_data)

        except json.JSONDecodeError:
            # Invalid JSON, log this too
            with open('csp-reports.txt', 'a') as file:
                file.write("JSON decoding error. Invalid JSON received.\n")

        return JsonResponse({'status': 'ok'})

store/views/decorators.py
from django.shortcuts import redirect
from store.models.user import UserRole, CustomUser

def admin_required(view_func):
    def wrapper(request, *args, **kwargs):
        # Print the user ID for debugging
        print("Logged-in user ID:", request.user.id)

        # Fetch the user roles
        user_roles = UserRole.objects.filter(user_id=request.user.id)

        # Print the user roles for debugging
        print("User roles retrieved:", [f"{role.user.username} - {role.role}" for role in user_roles])

        if any(role.role.name == 'admin' for role in user_roles):
            return view_func(request, *args, **kwargs)
        else:
            print("User is not an admin.")
            return redirect('/error')
    return wrapper

store/views/login.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.hashers import check_password
from store.models.user import CustomUser, UserRole
from django.views import View
from django.middleware.csrf import rotate_token
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect

@method_decorator(csrf_protect, name='dispatch')
class Login(View):
    return_url = None

    def get(self, request):
        Login.return_url = request.GET.get('next')
        return render(request, 'login.html')

    def post(self, request):
        rotate_token(request)
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            customer = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            customer = None
        error_message = None
        if customer:
            flag = check_password(password, customer.password)
            if flag:
                request.session['customer'] = customer.id
                user_roles = UserRole.objects.filter(user=customer)
                for user_role in user_roles:
                    role_name = user_role.role.name.lower()
                    if role_name == 'admin':
                        return redirect('admin_dashboard')
                    elif role_name == 'staff':
                        return redirect('staff_dashboard')
                
                # Redirect to the return_url or homepage if the user has no specific role
                if Login.return_url:
                    return HttpResponseRedirect(Login.return_url)
                else:
                    Login.return_url = None
                    return redirect('homepage')
            else:
                error_message = 'Invalid !!'
        else:
            error_message = 'Invalid !!'

        return render(request, 'login.html', {'error': error_message})

def logout(request):
    request.session.clear()
    return redirect('login')

store/templates/admin_dashboard.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-4">
    <h1 class="display-8 mb-3">Administrator Page</h1>
    <div class="list-group">
      <a href="/create_user" class="list-group-item list-group-item-action">Create User</a>
      <a href="/viewproducts" class="list-group-item list-group-item-action">View & Edit Products</a>
      <a href="/viewusers" class="list-group-item list-group-item-action">View Users</a>
      <a href="/vieworders" class="list-group-item list-group-item-action">View Orders & Edit Status</a>
      <a href="/viewcategories" class="list-group-item list-group-item-action">View & Edit Categories</a>
    </div>
  </div>
{% endblock %}

store/templates/createuser.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="display-8 mb-3">Create New User</h2>
    <form method="POST">
        <div class="list-group">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="first_name">
            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="last_name">
            <label for="phone_number">Phone Number:</label>
            <input type="text" id="phone_number" name="phone_number">
            <label for="user_type">User Type:</label>
            <select id="user_type" name="user_type">
                <option value="ADMIN">Admin</option>
                <option value="STAFF">Staff</option>
            </select>
        </div>
        <input type="submit" value="Create User">
    </form>
</div>
{% endblock %}

store/templates/editcategory.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2 class="display-4 mb-3">Edit Category</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ category.name }}">
            </div>
            <input type="submit" class="btn btn-primary" value="Save Changes">
        </form>
    </div>
{% endblock %}

store/templates/editorder.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="display-4 mb-3">Edit Order Status</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="status">Status:</label>
            <select class="form-control" id="status" name="status">
                <option value="pending" {% if order.status == False %}selected{% endif %}>Pending</option>
                <option value="paid" {% if order.status == True %}selected{% endif %}>Paid</option>
            </select>
        </div>
        <input type="submit" class="btn btn-primary" value="Save Status">
    </form>
</div>
{% endblock %}

store/templates/edituser.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2 class="display-4 mb-3">Edit User</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}">
            </div>
            <div class="form-group">
                <label for="first_name">First Name:</label>
                <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.first_name }}">
            </div>
            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.last_name }}">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label for="phone_number">Phone Number:</label>
                <input type="text" class="form-control" id="phone_number" name="phone_number" value="{{ user.phone_number }}">
            </div>
            <div class="form-group">
                <label for="role">Role:</label>
                <select class="form-control" id="role" name="role">
                    {% for role in roles %}
                        {% if user.userrole_set.exists %}
                            {% if role.id == user.userrole_set.first.role.id %}
                                <option value="{{ role.id }}" selected>{{ role.name }}</option>
                            {% else %}
                                <option value="{{ role.id }}">{{ role.name }}</option>
                            {% endif %}
                        {% else %}
                            <option value="{{ role.id }}">{{ role.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <input type="submit" class="btn btn-primary" value="Save Changes">
        </form>
    </div>
{% endblock %}

store/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load cart %}
{% load custom_filter %}

<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-lg-12 mx-auto">
            <form id="mainSearchForm" class="mb-3 form-inline">
                <input type="text" id="mainSearchInput" placeholder="Search for products..." class="form-control mb-2 mr-sm-2">
                <input type="submit" value="Search" class="btn btn-primary mb-2">
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" nonce="{{ request.nonce }}">
    document.getElementById('mainSearchForm').addEventListener('submit', function(event) {
        event.preventDefault();  // Prevents the default form submission behavior
        redirectToSearch();
    });
</script>


<!-- body -->
<div class="container-fluid mt-3">
    <div class="row">

        <!-- filter -->
        <div class="col-lg-3 mx-auto">
            <div class="list-group">
                <a href="/" class="list-group-item list-group-item-action btn btn-outline-success">All Products</a>

                {% for category in categories %}
                <a href="/?category={{category.id}}"
                    class="list-group-item list-group-item-action btn btn-outline-success ">{{category.name}}</a>
                {% endfor %}
            </div>
        </div>

        <!-- all products -->
        <div id='products' class="col-lg-9 mx-auto">
            <div class="row mx-auto">
                {% for product in products %}
                <style nonce="{{ request.nonce }}">
                    .product-card {
                        width: 18rem;
                    }
                </style>
                
                <div class="card mx-auto mb-3 product-card" id="{{product.id}}">
                                    <a href="/product/{{product.id}}">
                        <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <a href="/product/{{product.id}}">
                            <p class="card-title">{{product.name}}</p>
                        </a>
                        <p class="card-text"><b>{{product.price|currency}}</b></p>
                    </div>

                    <div class="card-footer p-0 no-gutters">
                        {% if product|is_in_cart:request.session.cart %}
                        <div class="row no-gutters">
                            <form action="/#{{product.id}}" class="col-2 " method="post">
                                {% csrf_token %}
                                <input hidden type="text" name='product' value='{{product.id}}'>
                                <input hidden type="text" name='remove' value='True'>
                                <input type="submit" value=" - " class="btn btn-block btn-success border-right">
                            </form>
                            <div class="text-center col btn btn-success">{{product|cart_quantity:request.session.cart}} in Cart</div>
                            <form action="/#{{product.id}}" class="col-2 " method="post">
                                {% csrf_token %}
                                <input hidden type="text" name='product' value='{{product.id}}'>
                                <input type="submit" value=" + " class="btn btn-block btn-success border-left">
                            </form>
                        </div>
                        {% else %}
                        <form action="/#{{product.id}}" method="POST" class="btn-block">
                            {% csrf_token %}
                            <input hidden type="text" name='product' value='{{product.id}}'>
                            <input type="submit" class="float-right btn btn-success form-control" value="Add To Cart">
                        </form>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" nonce="{{ request.nonce }}">
    window.onload = function() {
        var product_number = window.location.hash.substr(1);

        var product = document.getElementById(product_number);
        if (product) {
            product.scrollIntoView();
        }
    };

</script>



<script type="text/javascript" nonce="{{ request.nonce }}">
    function redirectToSearch() {
        var searchTerm = document.getElementById('mainSearchInput').value;
        window.location.href = "/search#" + encodeURIComponent(searchTerm);
    }
</script>

{% endblock %}

store/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="p-3 m-3">
        <div class="col-lg-5 rounded mx-auto border">

            <style nonce="{{ request.nonce }}">
                #loginHeader {
                    text-align: center;
                }
            </style>
            
            <h3 class="alert alert-light rounded-pill" id="loginHeader">Login</h3>
            
            <form action="/login" method="POST">

                {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}

                <!-- email -->
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id=""
                    value="{{values.email}}" 
                    class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>

                <!-- password -->
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" 
                    name="password" 
                    id=""
                     class="form-control form-control-sm" >
                </div>
                <!-- submit -->
                <style nonce="{{ request.nonce }}">
                    .login-button {
                        margin-bottom: 20px;
                    }
                </style>
                
                <button type="submit" class="btn btn-sm btn-success col-lg-12 rounded login-button">Login</button>
                            </form>
        </div>
    </div>
</div>

{% endblock %}

store/templates/newcategory.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2 class="display-4 mb-3">New Category</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" id="name" name="name">
            </div>
            <input type="submit" class="btn btn-primary" value="Create Category">
        </form>
    </div>
{% endblock %}

store/templates/viewusers.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2 class="display-4 mb-3">All Users</h2>
        {% for role in roles %}
            <h3>{{ role.name }}</h3>
            <ul class="list-group mb-4">
                {% for userrole in role.userrole_set.all %}
                    <li class="list-group-item">
                        <a href="{% url 'edituser' userrole.user.id %}">{{ userrole.user.first_name }} {{ userrole.user.last_name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </div>
{% endblock %}